### PR TITLE
feat: fix translation element assignment and add frontend debug mode for enhanced logging

### LINKED ISSUE #53: Still no translated news editable
Sorry, the error in https://github.com/xima-media/xima-typo3-frontend-edit/issues/43 has not been fixed after all. The problem is that the variable “Element” is overwritten. When an element is found, Element is invalid and the program jumps out. The element must also be “saved.” Therefore, the correction must look like this:

```      
     if (contentElement.element.l10n_source) {
        let l10nElement = document.querySelector(`#c${contentElement.element.l10n_source}`);
        if (l10nElement) {
          uid = contentElement.element.l10n_source;
          element = l10nElement;
        }
      }
```

I currently have no idea why the last correction worked for me. Sorry.

### PR DESCRIPTION
**Pull request by jackd248**
Fixes #53 

This PR also adds an optional frontend debug mode to show detailed information about the frontend assignment process.

Bildschirmfoto 2025-07-24 um 08 24 55

## Summary by CodeRabbit

- New Features
  - Added a Frontend Debug Mode setting to enable detailed browser console logs for content parsing and assignment.
  - When enabled, the frontend initializes with a debug flag to provide richer diagnostics, performance timings, and error reporting.
  - Enhanced handling of translated content elements during rendering with clearer logging when mappings are missing.

- Documentation
  - Added a “Debug” section describing the Frontend Debug Mode, its purpose, default state, and guidance to avoid using it in production.

### CODE REVIEW

File: Resources/Public/JavaScript/frontend_edit.js [hunk 1]
```diff
@@ -194,22 +255,77 @@ document.addEventListener('DOMContentLoaded', function () {
...
+        let l10nElement = document.querySelector(`#c${contentElement.element.l10n_source}`);
+        if (l10nElement) {
+          translationInfo = {
+            originalUid: uid,
+            translationSourceUid: contentElement.element.l10n_source,
+            language: contentElement.element.sys_language_uid || 'default'
+          };
           uid = contentElement.element.l10n_source;
+          element = l10nElement;
+          translationMappings++;
```
Comment (balasch) [inline Resources/Public/JavaScript/frontend_edit.js:281]: These three lines may only be executed if the condition in line 273 applies. So it happens again: `l10nElement` can be null, and then `element` is also deleted in line 280.

Comment (balasch) [reply Resources/Public/JavaScript/frontend_edit.js:281]: Sorry, I had tomatoes on my eyes and was looking at the wrong bracket. I will test it.
